// Mock data for Admin & Employee enterprise chat interactions

export const initialUsers = [
  {
    _id: "usr_admin_1",
    firstname: "Vikram",
    lastname: "Singhania",
    email: "vikram.singhania@enterprise.com",
    role: "admin",
    department: "Executive & Management",
    avatar: null,
    online: true,
    status: "active",
    lastSeen: "Online now",
    lastMessage: "Please review the updated Q3 performance reports by 5 PM.",
    lastMessageTime: "10:45 AM",
    unread: 2,
    phone: "+91 98765 43210",
  },
  {
    _id: "usr_emp_1",
    firstname: "Rahul",
    lastname: "Patel",
    email: "rahul.patel@enterprise.com",
    role: "employee",
    department: "Frontend Engineering",
    avatar: null,
    online: true,
    status: "active",
    lastSeen: "Online now",
    lastMessage: "The employee management module API integration is complete.",
    lastMessageTime: "10:38 AM",
    unread: 0,
    phone: "+91 98234 56789",
  },
  {
    _id: "usr_emp_2",
    firstname: "Ananya",
    lastname: "Deshmukh",
    email: "ananya.d@enterprise.com",
    role: "employee",
    department: "UI/UX Design",
    avatar: null,
    online: false,
    status: "active",
    lastSeen: "15m ago",
    lastMessage: "Uploaded the Figma wireframes for the new dashboard cards.",
    lastMessageTime: "09:15 AM",
    unread: 1,
    phone: "+91 98111 22334",
  },
  {
    _id: "usr_admin_2",
    firstname: "Priya",
    lastname: "Mehta",
    email: "priya.mehta@enterprise.com",
    role: "admin",
    department: "HR & Operations",
    avatar: null,
    online: false,
    status: "active",
    lastSeen: "Yesterday",
    lastMessage: "All team leave requests for next week have been approved.",
    lastMessageTime: "Yesterday",
    unread: 0,
    phone: "+91 98450 99887",
  },
  {
    _id: "usr_emp_3",
    firstname: "Amit",
    lastname: "Shah",
    email: "amit.shah@enterprise.com",
    role: "employee",
    department: "Backend & DevOps",
    avatar: null,
    online: true,
    status: "active",
    lastSeen: "Online now",
    lastMessage: "Database migration completed without any downtime.",
    lastMessageTime: "Yesterday",
    unread: 0,
    phone: "+91 98777 66554",
  },
  {
    _id: "usr_emp_4",
    firstname: "Karan",
    lastname: "Joshi",
    email: "karan.joshi@enterprise.com",
    role: "employee",
    department: "QA & Testing",
    avatar: null,
    online: false,
    status: "inactive",
    lastSeen: "2 days ago",
    lastMessage: "Logged 3 critical bug tickets in Jira for the chat sync.",
    lastMessageTime: "Mar 3",
    unread: 0,
    phone: "+91 98321 45670",
  },
  {
    _id: "usr_admin_3",
    firstname: "Neha",
    lastname: "Patel",
    email: "neha.patel@enterprise.com",
    role: "admin",
    department: "Product Strategy",
    avatar: null,
    online: true,
    status: "active",
    lastSeen: "Online now",
    lastMessage: "Sprint demo is scheduled for Thursday at 3 PM IST.",
    lastMessageTime: "Mar 2",
    unread: 3,
    phone: "+91 98654 32109",
  },
];

export const initialConversations = {
  usr_emp_1: [
    {
      id: "msg_1",
      senderId: "usr_emp_1",
      senderName: "Rahul Patel",
      senderRole: "employee",
      text: "Hello! Hope you are having a productive day.",
      timestamp: "10:30 AM",
      date: "Today",
      status: "read",
      reactions: [{ emoji: "👋", count: 1, users: ["me"] }],
    },
    {
      id: "msg_2",
      senderId: "me",
      senderName: "You",
      senderRole: "admin",
      text: "Hi Rahul! How is the progress on the latest sprint tasks?",
      timestamp: "10:32 AM",
      date: "Today",
      status: "read",
      reactions: [],
    },
    {
      id: "msg_3",
      senderId: "usr_emp_1",
      senderName: "Rahul Patel",
      senderRole: "employee",
      text: "The employee management module API integration is complete. All endpoints are verified and tested with JWT authentication.",
      timestamp: "10:36 AM",
      date: "Today",
      status: "read",
      reactions: [{ emoji: "🚀", count: 2, users: ["me", "usr_emp_1"] }],
      attachments: [
        {
          name: "API_Integration_Summary.pdf",
          size: "1.2 MB",
          type: "document",
        },
      ],
    },
    {
      id: "msg_4",
      senderId: "me",
      senderName: "You",
      senderRole: "admin",
      text: "Great work! I will review the pull request and trigger staging deployment shortly.",
      timestamp: "10:38 AM",
      date: "Today",
      status: "read",
      replyTo: {
        id: "msg_3",
        senderName: "Rahul Patel",
        text: "The employee management module API integration is complete...",
      },
      reactions: [{ emoji: "🙌", count: 1, users: ["usr_emp_1"] }],
    },
  ],
  usr_admin_1: [
    {
      id: "msg_v1",
      senderId: "usr_admin_1",
      senderName: "Vikram Singhania",
      senderRole: "admin",
      text: "Hi team, please ensure all milestone deliverables are updated before today's standup.",
      timestamp: "09:00 AM",
      date: "Today",
      status: "read",
      reactions: [{ emoji: "👍", count: 3, users: ["me"] }],
    },
    {
      id: "msg_v2",
      senderId: "usr_admin_1",
      senderName: "Vikram Singhania",
      senderRole: "admin",
      text: "Please review the updated Q3 performance reports by 5 PM.",
      timestamp: "10:45 AM",
      date: "Today",
      status: "delivered",
      attachments: [
        {
          name: "Q3_Performance_Overview.xlsx",
          size: "3.4 MB",
          type: "document",
        },
      ],
      reactions: [],
    },
  ],
  usr_emp_2: [
    {
      id: "msg_a1",
      senderId: "usr_emp_2",
      senderName: "Ananya Deshmukh",
      senderRole: "employee",
      text: "Hi! I just finished the new design system components for both Dark & Light themes.",
      timestamp: "09:10 AM",
      date: "Today",
      status: "read",
      reactions: [{ emoji: "🎨", count: 2, users: ["me", "usr_emp_2"] }],
    },
    {
      id: "msg_a2",
      senderId: "usr_emp_2",
      senderName: "Ananya Deshmukh",
      senderRole: "employee",
      text: "Uploaded the Figma wireframes for the new dashboard cards.",
      timestamp: "09:15 AM",
      date: "Today",
      status: "read",
      reactions: [],
    },
  ],
  usr_admin_2: [
    {
      id: "msg_p1",
      senderId: "usr_admin_2",
      senderName: "Priya Mehta",
      senderRole: "admin",
      text: "All team leave requests for next week have been approved.",
      timestamp: "04:30 PM",
      date: "Yesterday",
      status: "read",
      reactions: [{ emoji: "🎉", count: 2, users: ["me"] }],
    },
  ],
  usr_emp_3: [
    {
      id: "msg_am1",
      senderId: "usr_emp_3",
      senderName: "Amit Shah",
      senderRole: "employee",
      text: "Database migration completed without any downtime.",
      timestamp: "06:12 PM",
      date: "Yesterday",
      status: "read",
      reactions: [{ emoji: "🔥", count: 1, users: ["me"] }],
    },
  ],
  usr_emp_4: [
    {
      id: "msg_k1",
      senderId: "usr_emp_4",
      senderName: "Karan Joshi",
      senderRole: "employee",
      text: "Logged 3 critical bug tickets in Jira for the chat sync.",
      timestamp: "11:20 AM",
      date: "Mar 3",
      status: "read",
      reactions: [],
    },
  ],
  usr_admin_3: [
    {
      id: "msg_n1",
      senderId: "usr_admin_3",
      senderName: "Neha Patel",
      senderRole: "admin",
      text: "Sprint demo is scheduled for Thursday at 3 PM IST.",
      timestamp: "02:15 PM",
      date: "Mar 2",
      status: "read",
      reactions: [{ emoji: "🗓️", count: 2, users: ["me"] }],
    },
  ],
};
